# Generated by Django 5.1.2 on 2025-02-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'brands'},
        ),
    ]
