# Generated by Django 5.1.2 on 2025-02-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
    ]
